default_settings: null
behaviors:
  Ship:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0001
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
      memory: null
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 50000000
    time_horizon: 1024
    summary_freq: 25000
    threaded: true
    self_play: null
    behavioral_cloning: null
    framework: pytorch
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  seed: -1
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters:
  UnbreakableAsteroids:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 6418
          value: 10.0
      name: LessonZero
      completion_criteria:
        behavior: Ship
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: -0.2
        require_reset: true
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 6419
          value: 6.0
      name: LessonOne
      completion_criteria:
        behavior: Ship
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.6
        require_reset: true
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 6420
          value: 6.0
      name: LessonTwo
      completion_criteria:
        behavior: Ship
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.5
        require_reset: true
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 6421
          value: 0.0
      name: LessonThree
      completion_criteria: null
  BigAsteroids:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 6422
          value: 0.0
      name: LessonZero
      completion_criteria:
        behavior: Ship
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: -0.2
        require_reset: true
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 6423
          value: 0.0
      name: LessonOne
      completion_criteria:
        behavior: Ship
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.6
        require_reset: true
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 6424
          value: 0.0
      name: LessonTwo
      completion_criteria:
        behavior: Ship
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.5
        require_reset: true
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 6425
          value: 3.0
      name: LessonThree
      completion_criteria: null
  UFOs:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 6426
          value: 0.0
      name: LessonZero
      completion_criteria:
        behavior: Ship
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: -0.2
        require_reset: true
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 6427
          value: 0.0
      name: LessonOne
      completion_criteria:
        behavior: Ship
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.6
        require_reset: true
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 6428
          value: 1.0
      name: LessonTwo
      completion_criteria:
        behavior: Ship
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.5
        require_reset: true
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 6429
          value: 1.0
      name: LessonThree
      completion_criteria: null
checkpoint_settings:
  run_id: 32_MoveNShoot_DifferentCurriculum_changedCurriculum
  initialize_from: null
  load_model: false
  resume: true
  force: false
  train_model: false
  inference: false
debug: false
