default_settings: null
behaviors:
  Ship:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0001
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
      memory: null
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 50000000
    time_horizon: 1024
    summary_freq: 25000
    threaded: true
    self_play: null
    behavioral_cloning: null
    framework: pytorch
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  seed: -1
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters:
  UnbreakableAsteroids:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 9569
          value: 1.0
      name: OneUnbreakable
      completion_criteria:
        behavior: Ship
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.35
        require_reset: true
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 9570
          value: 2.0
      name: TwoUnbreakable
      completion_criteria:
        behavior: Ship
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.35
        require_reset: true
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 9571
          value: 0.0
      name: ThreeUnbreakale
      completion_criteria: null
  BigAsteroids:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 9572
          value: 0.0
      name: ZeroBig
      completion_criteria:
        behavior: Ship
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.35
        require_reset: true
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 9573
          value: 0.0
      name: ZeroBig2
      completion_criteria:
        behavior: Ship
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.35
        require_reset: true
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 9574
          value: 1.0
      name: OneBig
      completion_criteria:
        behavior: Ship
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.5
        require_reset: true
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 9575
          value: 2.0
      name: TwoBig
      completion_criteria: null
checkpoint_settings:
  run_id: 18_MoveNShoot_CurriculumLearning_MoreUnbreakables_HigherTimeHorizon_HigherTimePenalty
  initialize_from: null
  load_model: false
  resume: true
  force: false
  train_model: false
  inference: false
debug: false
