behaviors:
  Ship:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 1e-2
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      curiosity:
        strength: 0.075
        gamma: 0.995
        encoding_size: 128
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 512
    summary_freq: 10000
    threaded: true
